require 'core.options'
require 'core.keymaps'
require 'core.autocmds'

require 'plugins.ui'
require 'plugins.telescope'
require 'plugins.lsp'
require 'plugins.completion'
require 'plugins.formatting'
require 'plugins.treesitter'
require 'plugins.gitsigns'
require 'plugins.git-conflict'
require 'plugins.diffview'
require 'plugins.debug'
require 'plugins.lint'
require 'plugins.filetree'
require 'plugins.testing'
require 'plugins.flutter'
require 'plugins.markdown'
require 'plugins.zenmode'

-- vim: ts=2 sts=2 sw=2 et
