# Blueman
for_window [app_id="blueman-manager"] {
    floating enable
    move position center
}

# Browsers: tag + inhibit idle when fullscreen
for_window [class="Chromium-browser"] mark Browser
for_window [class="Brave-browser"] mark Browser
for_window [class="firefox"]  mark Browser
for_window [app_id="Chromium-browser"] mark Browser
for_window [app_id="brave-browser"] mark Browser
for_window [app_id="firefox"] mark Browser
for_window [con_mark="Browser"] {
    inhibit_idle fullscreen
}
for_window [app_id="firefox" title="Firefox — Sharing Indicator"] {
    floating enable
}

# Pavucontrol
for_window [app_id="pwvucontrol"] {
    floating enable
    move position center
}

# Polkit agent
for_window [app_id="lxqt-policykit-agent"] {
    floating enable
    move position center
}

# Thunar rename
for_window [app_id="thunar" title="^Rename.*"] {
    floating enable
    move position center
}

# Geary file picker.
for_window [app_id="geary" title="^Geary$"] {
    floating enable
    move position center
}
